image: node:lts-trixie

stages:
  - build
  - pages

build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm install -g @angular/cli
    - ng build main --configuration=sextant --base-href "/geonetwork5/"
    # Déplacer le build Angular dans public/ pour GitLab Pages
    - mkdir -p ../public
    - cp -r dist/main/browser/. ../public/.
    # pour la gestion gitlab-pages / nginx
    - cp dist/main/browser/index.html ../public/404.html

    # Build pour sextant-test
    # transforme le nom de la branche (remplace / par _)
    - branch_transformed_name=`echo $CI_COMMIT_REF_NAME | sed 's/\//_/g'`
    - ng build main --configuration=sextant --base-href "/www/GN5/catalogue/branches/$branch_transformed_name/public_sextant-test/"
    - mkdir -p ../public_sextant-test
    - cp -r dist/main/browser/. ../public_sextant-test/.

  artifacts:
    paths:
      - public
      - public_sextant-test
    expire_in: 4 weeks

pages:
  stage: pages
  script:
    - echo "Publishing GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
