image: 22-trixie-slim

stages:
  - build
  - pages

variables:
  MAVEN_OPTS: "-Dmaven.test.skip=true"

cache:
  paths:
    - .m2/repository
    - frontend/node_modules/

build_gn5:
  stage: build
  script:
    # 1. Installer Angular CLI
    - npm install -g @angular/cli

    # 2. Build Angular main
    - cd frontend
    - npm install
    - ng build main --configuration=sextant --base-href "/geonetwork5/"

    # 3. Déplacer le build Angular dans public/ pour GitLab Pages
    - mkdir -p ../public
    - cp -r dist/main/browser/* ../public/

  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: pages
  script:
    - echo "Publishing GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
