geonetwork:
  tasks:
    data-ingester:
      resources:
        - type: "dataset"
          properties:
            - name: "name"
              help: "Set the title of the dataset if not set and not starts with 'Copy of'"
              context: "DatasetLayer"
              operations:
                - schema: "iso19139"
                  operation: "gn_delete"
                  xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString"
                  condition: "starts-with(./gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString, 'Copy of')"
                - schema: "iso19139"
                  operation: "gn_create"
                  xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString"
                  condition: "starts-with(./gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString, 'Copy of')  or count(./mdb:identificationInfo/*/mri:citation/*/cit:title) = 0"
                  value: "{{title}}"

                - schema: "iso19115-3.2018"
                  operation: "gn_delete"
                  xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:citation/cit:CI_Citation/cit:title/gco:CharacterString"
                  condition: "starts-with(./mdb:identificationInfo/*/mri:citation/*/cit:title/gco:CharacterString, 'Copy of')"
                - schema: "iso19115-3.2018"
                  operation: "gn_create"
                  xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:citation/cit:CI_Citation/cit:title/gco:CharacterString"
                  condition: "starts-with(./mdb:identificationInfo/*/mri:citation/*/cit:title/gco:CharacterString, 'Copy of') or count(./mdb:identificationInfo/*/mri:citation/*/cit:title) = 0"
                  value: "{{title}}"


            - name: "spatialRepresentationType"
              help: "Set the spatial representation type of the dataset. If not set, it will be set to 'vector'"
              context: "DatasetLayer"
              operations:
                - schema: "iso19139"
                  operation: "gn_delete"
                  xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:spatialRepresentationType"
                - schema: "iso19139"
                  operation: "gn_create"
                  xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:spatialRepresentationType"
                  value:  >
                    <gmd:spatialRepresentationType>
                          <gmd:MD_SpatialRepresentationTypeCode
                                codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_SpatialRepresentationTypeCode"
                                codeListValue="{{datasetType:-vector}}" />
                        </gmd:spatialRepresentationType>

                - schema: "iso19115-3.2018"
                  operation: "gn_delete"
                  xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:spatialRepresentationType"
                - schema: "iso19115-3.2018"
                  operation: "gn_create"
                  xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:spatialRepresentationType"
                  value: >
                    <mri:spatialRepresentationType xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0"
                                     xmlns:mcc="http://standards.iso.org/iso/19115/-3/mcc/1.0">
                      <mcc:MD_SpatialRepresentationTypeCode
                            codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_SpatialRepresentationTypeCode"
                            codeListValue="{{datasetType:-vector}}"/>
                    </mri:spatialRepresentationType>

            - name: "latLonBoundingBox"
              help: "Replace existing geographic bounding box"
              context: "DatasetLayer"
              operations:
                - schema: "iso19139"
                  operation: "gn_delete"
                  xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent[gco:nilReason='computedFromDatasource']/gmd:EX_Extent/gmd:geographicElement"
                - schema: "iso19139"
                  operation: "gn_create"
                  xpath: "gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent"
                  value: >
                    <gmd:extent xmlns:gco="http://www.isotc211.org/2005/gco"
                                         xmlns:gmd="http://www.isotc211.org/2005/gmd"
                                         gco:nilReason="computedFromDatasource">
                      <gmd:EX_Extent>
                        <gmd:geographicElement>
                          <gmd:EX_GeographicBoundingBox>
                            <gmd:westBoundLongitude>
                              <gco:Decimal>{{west:--180}}</gco:Decimal>
                            </gmd:westBoundLongitude>
                            <gmd:eastBoundLongitude>
                              <gco:Decimal>{{east:-180}}</gco:Decimal>
                            </gmd:eastBoundLongitude>
                            <gmd:southBoundLatitude>
                              <gco:Decimal>{{south:--90}}</gco:Decimal>
                            </gmd:southBoundLatitude>
                            <gmd:northBoundLatitude>
                              <gco:Decimal>{{north:-90}}</gco:Decimal>
                            </gmd:northBoundLatitude>
                          </gmd:EX_GeographicBoundingBox>
                        </gmd:geographicElement>
                      </gmd:EX_Extent>
                    </gmd:extent>

                - schema: "iso19115-3.2018"
                  operation: "gn_delete"
                  xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:extent[gco:nilReason='computedFromDatasource']/gex:EX_Extent/gex:geographicElement"
                - schema: "iso19115-3.2018"
                  operation: "gn_create"
                  xpath: "mdb:identificationInfo/mri:MD_DataIdentification/mri:extent "
                  value: >
                    <mri:extent xmlns:mri="http://standards.iso.org/iso/19115/-3/mri/1.0"
                                         xmlns:gex="http://standards.iso.org/iso/19115/-3/gex/1.0"
                                         xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
                                         gco:nilReason="computedFromDatasource">
                     <gex:extent>
                       <gex:EX_Extent>
                         <gex:geographicElement>
                           <gex:EX_GeographicBoundingBox>
                             <gex:westBoundLongitude>
                               <gco:Decimal>{{west:--180}}</gco:Decimal>
                             </gex:westBoundLongitude>
                             <gex:eastBoundLongitude>
                               <gco:Decimal>{{east:-180}}</gco:Decimal>
                             </gex:eastBoundLongitude>
                             <gex:southBoundLatitude>
                               <gco:Decimal>{{south:--90}}</gco:Decimal>
                             </gex:southBoundLatitude>
                             <gex:northBoundLatitude>
                               <gco:Decimal>{{north:-90}}</gco:Decimal>
                             </gex:northBoundLatitude>
                           </gex:EX_GeographicBoundingBox>
                         </gex:geographicElement>
                       </gex:EX_Extent>
                     </gex:extent>
                    </mri:extent>


            - name: "vectorSpatialRepresentation"
              # TODO: Raster support
              help: "For each layers, set the feature count and geometry type if geometry column found."
              context: "DatasetLayer"
              operations:
                - schema: "iso19139"
                  xpath: "gmd:spatialRepresentationInfo[@gco:nilReason = 'computedFromDatasource']"
                  operation: "gn_delete"
                - schema: "iso19139"
                  xpath: "gmd:spatialRepresentationInfo"
                  operation: "gn_create"
                  value: >
                    <gmd:spatialRepresentationInfo
                               xmlns:gco="http://www.isotc211.org/2005/gco"
                               xmlns:gmd="http://www.isotc211.org/2005/gmd"
                               gco:nilReason="computedFromDatasource">
                               <gmd:MD_VectorSpatialRepresentation>
                                 <gmd:geometricObjects>
                                   <gmd:MD_GeometricObjects>
                                     <gmd:geometricObjectType>
                                       <gmd:MD_GeometricObjectTypeCode
                                         codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_GeometricObjectTypeCode"
                                         codeListValue="{{geometryType:-unknown}}"/>
                                     </gmd:geometricObjectType>
                                     <gmd:geometricObjectCount>
                                       <gco:Integer>{{featureCount}}</gco:Integer>
                                     </gmd:geometricObjectCount>
                                   </gmd:MD_GeometricObjects>
                                 </gmd:geometricObjects>
                               </gmd:MD_VectorSpatialRepresentation>
                             </gmd:spatialRepresentationInfo>


                - schema: "iso19115-3.2018"
                  operation: "gn_delete"
                  xpath: "mdb:spatialRepresentationInfo[@gco:nilReason = 'computedFromDatasource']"
                - schema: "iso19115-3.2018"
                  operation: "gn_create"
                  xpath: "mdb:spatialRepresentationInfo"
                  value: >
                    <mdb:spatialRepresentationInfo xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0"
                                                             xmlns:msr="http://standards.iso.org/iso/19115/-3/msr/2.0"
                                                             xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
                                                             gco:nilReason="computedFromDatasource">
                                <msr:MD_VectorSpatialRepresentation>
                                  <msr:geometricObjects>
                                    <msr:MD_GeometricObjects>
                                      <msr:geometricObjectType>
                                        <msr:MD_GeometricObjectTypeCode
                                          codeList="http://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_GeometricObjectTypeCode"
                                          codeListValue="{{geometryType:-unknown}}"/>
                                      </msr:geometricObjectType>
                                      <msr:geometricObjectCount>
                                       <gco:Integer>{{featureCount}}</gco:Integer>
                                      </msr:geometricObjectCount>
                                    </msr:MD_GeometricObjects>
                                  </msr:geometricObjects>
                                </msr:MD_VectorSpatialRepresentation>
                              </mdb:spatialRepresentationInfo>


            - name: "distributionFormat"
              help: "Set the distribution format of the dataset based on the data analyzer driver information."
              context: "DatasetLayer"
              operations:
                - schema: "iso19139"
                  operation: "gn_delete"
                  xpath: "gmd:distributionInfo/gmd:MD_Distribution/gmd:distributionFormat[*/gmd:name/*/text() ='{{formatDescription}}']"
                - schema: "iso19139"
                  operation: "gn_create"
                  xpath: "gmd:distributionInfo/gmd:MD_Distribution"
                  value:  >
                    <gmd:distributionFormat
                        xmlns:gco="http://www.isotc211.org/2005/gco"
                        xmlns:gmd="http://www.isotc211.org/2005/gmd"
                        gco:nilReason="computedFromDatasource">
                        <gmd:MD_Format>
                          <gmd:name>
                            <gco:CharacterString>{{formatDescription:-}}</gco:CharacterString>
                          </gmd:name>
                          <gmd:version gco:nilReason="unknown">
                            <gco:CharacterString/>
                          </gmd:version>
                        </gmd:MD_Format>
                      </gmd:distributionFormat>

                - schema: "iso19115-3.2018"
                  operation: "gn_delete"
                  xpath: "mdb:distributionInfo/mrd:MD_Distribution/mri:distributionFormat[*/mrd:formatSpecificationCitation/*/cit:name/*/text() ='{{formatDescription}}']"
                - schema: "iso19115-3.2018"
                  operation: "gn_create"
                  xpath: "mdb:distributionInfo/mrd:MD_Distribution"
                  value: >
                    <mrd:distributionFormat xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0"
                                                      xmlns:msr="http://standards.iso.org/iso/19115/-3/msr/2.0"
                                                      xmlns:cit="http://standards.iso.org/iso/19115/-3/cit/2.0"
                                                      xmlns:mrd="http://standards.iso.org/iso/19115/-3/mrd/1.0"
                                                      xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
                                                      gco:nilReason="computedFromDatasource">
                                <mrd:MD_Format>
                                  <mrd:formatSpecificationCitation>
                                    <cit:CI_Citation>
                                      <cit:title>
                                        <gco:CharacterString>{{formatDescription:-}}</gco:CharacterString>
                                      </cit:title>
                                      <cit:alternateTitle>
                                        <gco:CharacterString>{{format:-}}</gco:CharacterString>
                                      </cit:alternateTitle>
                                    </cit:CI_Citation>
                                  </mrd:formatSpecificationCitation>
                                </mrd:MD_Format>
                              </mrd:distributionFormat>


            - name: "featureCatalogue"
              help: "Add feature catalogue information to the dataset if not exists."
              context: "DatasetLayer"
              operations:
                # Not supported in iso19139
                - schema: "iso19115-3.2018"
                  operation: "gn_add"
                  xpath: "."
                  condition: "count(mdb:contentInfo[@uuid='fc/{{featureTypeName}}']) = 0"
                  value: >
                    <mdb:contentInfo xmlns:mdb="http://standards.iso.org/iso/19115/-3/mdb/2.0"
                                               xmlns:mrc="http://standards.iso.org/iso/19115/-3/mrc/2.0"
                                               xmlns:cat="http://standards.iso.org/iso/19115/-3/cat/1.0"
                                               xmlns:gfc="http://standards.iso.org/iso/19110/gfc/1.1"
                                               xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0"
                                               uuid="fc/{{featureTypeName}}">
                                <mrc:MD_FeatureCatalogue>
                                  <mrc:featureCatalogue>
                                    <gfc:FC_FeatureCatalogue>
                                      <cat:name>
                                        <gco:CharacterString>{{featureTypeName}}</gco:CharacterString>
                                      </cat:name>
                                      <cat:scope gco:nilReason="missing">
                                        <gco:CharacterString/>
                                      </cat:scope>
                                      <cat:versionNumber gco:nilReason="missing">
                                        <gco:CharacterString/>
                                      </cat:versionNumber>
                                    </gfc:FC_FeatureCatalogue>
                                  </mrc:featureCatalogue>
                                </mrc:MD_FeatureCatalogue>
                              </mdb:contentInfo>

            - name: "featureType"
              context: "DatasetLayer"
              operations:
                - schema: "iso19115-3.2018"
                  operation: "gn_add"
                  xpath: "/mdb:contentInfo[@uuid = 'fc/{{featureTypeName}}']/*/mrc:featureCatalogue/*"
                  condition: "count(mdb:contentInfo[@uuid = 'fc/{{featureTypeName}}']/*/mrc:featureCatalogue/*/gfc:featureType[*/gfc:typeName = '{{featureTypeName}}']) = 0"
                  value: >
                      <gfc:featureType xmlns:mrc="http://standards.iso.org/iso/19115/-3/mrc/2.0"
                        xmlns:cat="http://standards.iso.org/iso/19115/-3/cat/1.0"
                        xmlns:gfc="http://standards.iso.org/iso/19110/gfc/1.1"
                        xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0">
                          <gfc:FC_FeatureType>
                            <gfc:typeName>{{featureTypeName}}</gfc:typeName>
                            <gfc:isAbstract>
                            <gco:Boolean>false</gco:Boolean>
                            </gfc:isAbstract>
                          </gfc:FC_FeatureType>
                        </gfc:featureType>

            - name: "featureTypeColumns"
              context: "DatasetColumns"
              operations:
                - schema: "iso19115-3.2018"
                  operation: "gn_add"
                  xpath: "/mdb:contentInfo[@uuid = 'fc/{{featureTypeName}}']/*/mrc:featureCatalogue/*/gfc:featureType/*[gfc:typeName = '{{featureTypeName}}']"
                  condition: "count(mdb:contentInfo[@uuid = 'fc/{{featureTypeName}}']/*/mrc:featureCatalogue/*/gfc:featureType/*[gfc:typeName = '{{featureTypeName}}']/gfc:carrierOfCharacteristics[*/gfc:memberName = '{{fieldName}}']) = 0"
                  value: >
                    <gfc:carrierOfCharacteristics xmlns:mrc="http://standards.iso.org/iso/19115/-3/mrc/2.0"
                                                                             xmlns:cat="http://standards.iso.org/iso/19115/-3/cat/1.0"
                                                                             xmlns:gfc="http://standards.iso.org/iso/19110/gfc/1.1"
                                                                             xmlns:gco="http://standards.iso.org/iso/19115/-3/gco/1.0">
                      <gfc:FC_FeatureAttribute>
                        <gfc:memberName>{{fieldName:-}}</gfc:memberName>
                        <gfc:definition>
                          <gco:CharacterString>{{fieldDescription:-}}</gco:CharacterString>
                        </gfc:definition>
                        <gfc:valueType>
                          <gco:TypeName>
                            <gco:aName>
                              <gco:CharacterString>{{fieldType:-}}</gco:CharacterString>
                            </gco:aName>
                          </gco:TypeName>
                        </gfc:valueType>
                      </gfc:FC_FeatureAttribute>
                    </gfc:carrierOfCharacteristics>

