/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OgcApiRecordsFacetSummaryDto } from './ogcApiRecordsFacetSummaryDto';
import { OgcApiRecordsLinkDto } from './ogcApiRecordsLinkDto';
import { OgcApiRecordsLinkTemplateDto } from './ogcApiRecordsLinkTemplateDto';
import { OgcApiRecordsRecordGeoJSONDto } from './ogcApiRecordsRecordGeoJSONDto';

export interface OgcApiRecordsGetRecords200ResponseDto {
  type: OgcApiRecordsGetRecords200ResponseDto.TypeEnum;
  facets?: { [key: string]: OgcApiRecordsFacetSummaryDto };
  features: Array<OgcApiRecordsRecordGeoJSONDto>;
  links?: Array<OgcApiRecordsLinkDto>;
  timeStamp?: string;
  numberMatched?: number;
  numberReturned?: number;
  linkTemplates?: Array<OgcApiRecordsLinkTemplateDto>;
}
export namespace OgcApiRecordsGetRecords200ResponseDto {
  export const TypeEnum = {
    FeatureCollection: 'FeatureCollection',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
