/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Contact } from './contact';
import { ProcessStepSource } from './processStepSource';

export interface ProcessStep {
  descriptionObject?: { [key: string]: string };
  date?: string;
  source?: Array<ProcessStepSource>;
  processor?: Array<Contact>;
}
