/**
 * GeoNetwork API
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Keyword {
  default: string;
  link?: string | null;
  [key: string]: string | null | undefined;
}

export interface Thesaurus {
  id?: string;
  title?: string;
  multilingualTitle?: { [key: string]: string };
  theme?: string;
  link?: string;
  keywords?: Array<Keyword>;
  field?: string;
}
