/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MapServer } from './mapServer';

export interface AnonymousMapserver {
  configurl?: string;
  description?: string;
  id?: number;
  name?: string;
  namespace?: string;
  namespacePrefix?: string;
  password?: string;
  pushStyleInWorkspace?: MapServer;
  pushStyleInWorkspace_JpaWorkaround?: string;
  stylerurl?: string;
  username?: string;
  wcsurl?: string;
  wfsurl?: string;
  wmsurl?: string;
}
