/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DOI server details
 */
export interface DoiServerDto {
  description?: string;
  id?: number;
  landingPageTemplate?: string;
  name?: string;
  password?: string;
  pattern?: string;
  prefix?: string;
  publicUrl?: string;
  publicationGroups?: Set<number>;
  url?: string;
  username?: string;
}
