/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Description } from './description';
import { FeatureType } from './featureType';
import { MultilingualValue } from './multilingualValue';

export interface FCRelatedMetadataItem {
  description: Description;
  featureType: FeatureType;
  hash?: string;
  id?: string;
  idx?: string;
  mdType: Array<string>;
  origin?: string;
  title: MultilingualValue;
  type?: string;
  url?: MultilingualValue;
}
