/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ISODate } from './iSODate';
import { LinkStatus } from './linkStatus';
import { MetadataLink } from './metadataLink';

export interface Link {
  id?: number;
  lastCheck?: ISODate;
  lastState?: number;
  linkStatus?: Set<LinkStatus>;
  linkType?: Link.LinkTypeEnum;
  protocol?: string;
  records?: Set<MetadataLink>;
  url?: string;
}
export namespace Link {
  export const LinkTypeEnum = {
    Http: 'HTTP',
    Metadata: 'METADATA',
  } as const;
  export type LinkTypeEnum = (typeof LinkTypeEnum)[keyof typeof LinkTypeEnum];
}
