/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Identifier template details
 */
export interface MetadataIdentifierTemplate {
  id?: number;
  name?: string;
  systemDefault?: boolean;
  systemProvided?: boolean;
  systemProvided_JPAWorkaround?: string;
  template?: string;
}
