/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ISODate } from './iSODate';
import { StatusValue } from './statusValue';

export interface MetadataStatusDto {
  changeDate?: ISODate;
  changeMessage?: string;
  closeDate?: ISODate;
  currentState?: string;
  dueDate?: ISODate;
  id?: number;
  metadataId?: number;
  owner?: number;
  previousState?: string;
  relatedMetadataStatusId?: number;
  statusValue?: StatusValue;
  titles?: { [key: string]: string };
  userId?: number;
  uuid?: string;
}
