/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchematronValidationReport } from './schematronValidationReport';
import { InfoReport } from './infoReport';

export interface MetadataValidationProcessingReport {
  ellapsedTimeInSeconds?: number;
  endIsoDateTime?: string;
  invalidMetadata?: { [key: string]: InfoReport };
  metadata?: Set<number>;
  metadataWithWarnings?: { [key: string]: InfoReport };
  numberOfInvalidRecords?: number;
  numberOfNullRecords?: number;
  numberOfRecords?: number;
  numberOfRecordsNotEditable?: number;
  numberOfRecordsProcessed?: number;
  numberOfRecordsWithValidationWarnings?: number;
  numberOfValidRecords?: number;
  running?: boolean;
  startIsoDateTime?: string;
  totalRecords?: number;
  totalTimeInSeconds?: number;
  type?: string;
  uuid?: string;
  validMetadata?: { [key: string]: InfoReport };
  validationErrors?: { [key: string]: Array<SchematronValidationReport> };
  validationWarnings?: { [key: string]: Array<SchematronValidationReport> };
}
