/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Report } from './report';
import { InfoReport } from './infoReport';

export interface ProcessingReport {
  ellapsedTimeInSeconds?: number;
  endIsoDateTime?: string;
  errors?: Array<Report>;
  infos?: Array<InfoReport>;
  running?: boolean;
  startIsoDateTime?: string;
  totalTimeInSeconds?: number;
  type?: string;
  uuid?: string;
}
