/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservedOperation } from './reservedOperation';
import { ReservedGroup } from './reservedGroup';

export interface PublicationOption {
  additionalPublications?: { [key: string]: Array<ReservedOperation> };
  name?: string;
  publicationGroup?: ReservedGroup;
  publicationOperations?: Array<ReservedOperation>;
}
export namespace PublicationOption {}
