/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RegionResponse {
  categoryId?: string;
  east?: number;
  hasGeom?: boolean;
  id?: string;
  label?: { [key: string]: string };
  north?: number;
  south?: number;
  west?: number;
}
