/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Associated } from './associated';
import { Parent } from './parent';
import { Dataset } from './dataset';
import { Service } from './service';
import { Thumbnail } from './thumbnail';
import { Fcat } from './fcat';
import { Related } from './related';
import { Children } from './children';
import { Hasfeaturecats } from './hasfeaturecats';
import { Hassource } from './hassource';
import { Online } from './online';
import { RelatedSource } from './relatedSource';
import { Siblings } from './siblings';

export interface RelatedResponse {
  associated?: Associated;
  children?: Children;
  datasets?: Dataset;
  fcats?: Fcat;
  hasfeaturecats?: Hasfeaturecats;
  hassources?: Hassource;
  onlines?: Online;
  parent?: Parent;
  related?: Related;
  services?: Service;
  siblings?: Siblings;
  sources?: RelatedSource;
  thumbnails?: Thumbnail;
}
