/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const RelatedItemType = {
  Children: 'children',
  Parent: 'parent',
  BrothersAndSisters: 'brothersAndSisters',
  Siblings: 'siblings',
  Associated: 'associated',
  Services: 'services',
  Datasets: 'datasets',
  Fcats: 'fcats',
  Hasfeaturecats: 'hasfeaturecats',
  Sources: 'sources',
  Hassources: 'hassources',
  Related: 'related',
  Onlines: 'onlines',
  Thumbnails: 'thumbnails',
} as const;
export type RelatedItemType = (typeof RelatedItemType)[keyof typeof RelatedItemType];
