/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Setting {
  dataType?: Setting.DataTypeEnum;
  editable?: boolean;
  editable_JpaWorkaround?: string;
  encrypted?: boolean;
  encrypted_JpaWorkaround?: string;
  internal?: boolean;
  internal_JpaWorkaround?: string;
  name?: string;
  position?: number;
  storedValue?: string;
  value?: string;
}
export namespace Setting {
  export const DataTypeEnum = {
    String: 'STRING',
    Int: 'INT',
    Boolean: 'BOOLEAN',
    Json: 'JSON',
  } as const;
  export type DataTypeEnum = (typeof DataTypeEnum)[keyof typeof DataTypeEnum];
}
