/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfoReport } from './infoReport';
import { Report } from './report';

export interface SimpleMetadataProcessingReport {
  ellapsedTimeInSeconds?: number;
  endIsoDateTime?: string;
  errors?: Array<Report>;
  infos?: Array<InfoReport>;
  metadata?: Set<number>;
  metadataErrors?: { [key: string]: Array<Report> };
  metadataInfos?: { [key: string]: Array<InfoReport> };
  numberOfNullRecords?: number;
  numberOfRecordNotFound?: number;
  numberOfRecords?: number;
  numberOfRecordsNotEditable?: number;
  numberOfRecordsProcessed?: number;
  numberOfRecordsUnchanged?: number;
  numberOfRecordsWithErrors?: number;
  running?: boolean;
  startIsoDateTime?: string;
  totalRecords?: number;
  totalTimeInSeconds?: number;
  type?: string;
  uuid?: string;
}
