/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Status {
  date?: string;
  id?: string;
  message?: string;
  state?: Status.StateEnum;
}
export namespace Status {
  export const StateEnum = {
    Red: 'RED',
    Uninitialized: 'UNINITIALIZED',
    Yellow: 'YELLOW',
    Green: 'GREEN',
    Disabled: 'DISABLED',
  } as const;
  export type StateEnum = (typeof StateEnum)[keyof typeof StateEnum];
}
