/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';

export interface UserDto {
  addresses?: Array<Address>;
  email?: UserDto;
  emailAddresses?: Array<string>;
  enabled?: boolean;
  groupsEditor?: Array<string>;
  groupsRegisteredUser?: Array<string>;
  groupsReviewer?: Array<string>;
  groupsUserAdmin?: Array<string>;
  id?: string;
  kind?: string;
  name?: string;
  organisation?: string;
  password?: string;
  profile?: string;
  surname?: string;
  username?: string;
}
