/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserSecurity {
  authType?: string;
  nodeId?: string;
  securityNotifications?: Set<UserSecurity.SecurityNotificationsEnum>;
  securityNotificationsString?: UserSecurity;
}
export namespace UserSecurity {
  export const SecurityNotificationsEnum = {
    UpdateHashRequired: 'UPDATE_HASH_REQUIRED',
    Unknown: 'UNKNOWN',
  } as const;
  export type SecurityNotificationsEnum =
    (typeof SecurityNotificationsEnum)[keyof typeof SecurityNotificationsEnum];
}
