/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserFeedbackDTO {
  approverName?: string;
  authorEmail?: string;
  authorName?: string;
  authorOrganization?: string;
  authorUserId?: number;
  captcha?: string;
  comment?: string;
  date?: string;
  keywords?: Array<string>;
  metadataTitle?: string;
  metadataUUID?: string;
  optionPrivacy?: boolean;
  parentUuid?: string;
  published?: boolean;
  rating?: { [key: string]: number };
  ratingAVG?: number;
  showApproveButton?: boolean;
  uuid?: string;
}
