/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserGroupId {
  groupId?: number;
  profile?: UserGroupId.ProfileEnum;
  userId?: number;
}
export namespace UserGroupId {
  export const ProfileEnum = {
    Administrator: 'Administrator',
    UserAdmin: 'UserAdmin',
    Reviewer: 'Reviewer',
    Editor: 'Editor',
    RegisteredUser: 'RegisteredUser',
    Guest: 'Guest',
    Monitor: 'Monitor',
  } as const;
  export type ProfileEnum = (typeof ProfileEnum)[keyof typeof ProfileEnum];
}
