/**
 * GeoNetwork 4.4.10 OpenAPI Documentation
 *
 * Contact: geonetwork-users@lists.sourceforge.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Group } from './group';
import { User } from './user';
import { UserGroupId } from './userGroupId';

export interface UserGroup {
  group?: Group;
  id?: UserGroupId;
  profile?: UserGroup.ProfileEnum;
  user?: User;
}
export namespace UserGroup {
  export const ProfileEnum = {
    Administrator: 'Administrator',
    UserAdmin: 'UserAdmin',
    Reviewer: 'Reviewer',
    Editor: 'Editor',
    RegisteredUser: 'RegisteredUser',
    Guest: 'Guest',
    Monitor: 'Monitor',
  } as const;
  export type ProfileEnum = (typeof ProfileEnum)[keyof typeof ProfileEnum];
}
